backend:
  name: github
  repo: dedalizonte/test-ca
  branch: main

media_folder: "docs/img"
public_folder: "/img"

collections:
  - name: "paginas"
    label: "Páginas de Ayuda"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }

backend:
  name: github
  repo: dedalizonte/test-ca
  branch: main
  auth_scope: repo
  base_url: https://auth.netlify.com
  site_domain: dedalizonte.github.io
  auth_endpoint: api/v1/auth
  client_id: Ov23livKCl7k9k6zAFkG
